### ISSUE TITLE
Guac's Roadmap (v0)

### ISSUE THREAD

**Issue by aarvinr** [aarvinr/guac#1]
This issue contains the roadmap & feature lookahead for Guac v0. It will be continuously updated until it's time to move on to v1, if we make it there. Thanks to anyone who flags issues or contributes code 🙌.

> [!NOTE]
> Credit goes to [HTMX](https://htmx.org/) and [Alpine](https://alpinejs.dev/) for **heavy** inspiration.

## Roadmap
- [ ] `hreq`: Sends `:method` request to `"url"` on trigger.
- [ ] `on`: Triggers on `"event"`.
  - [ ] `load`: Triggers once when element loaded.
  - [ ] `reveal`: Triggers once when element viewed.
  - [ ] `on:changed`: Triggers once if value changed.
  - [ ] `on:wait`: Triggers after `"time"` (milliseconds), **resets on subsequent triggers**.
  - [ ] `on:hold`: Triggers after `"time"` (milliseconds), **discards on subsequent triggers**.
  - [ ] `on:from`: Triggers on `"element"`.
  - [ ] `on:filter`: Triggers if meets `"filter"`.
- [ ] `poll`: Repeatedly triggers per `"time"` (milliseconds).
- [ ] `load`: Shows `"element"` until request received.
- [ ] `target`: Loads data onto `"element"`.
- [ ] `swap`: Swaps `"replace"` of target with received.
  - [ ] `swap:wait`: Swaps after `"time"` (milliseconds).
  - [ ] `swap:title`: Swaps any title found in new content.
  - [ ] `swap:scroll`: Scrolls into view.
- [ ] `enhance`: Uses AJAX swapping instead of reloading the whole page.
